default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wikipages_development

test:
  <<: *default
  database: wikipages_test

production:
  <<: *default
  database: wikipages_production
  username: wikipages
  password: <%= ENV['WIKIPAGES_DATABASE_PASSWORD'] %>
